import * as fs from 'fs'
import * as path from 'path'

// Script directory (works with tsx)
const scriptDir = path.dirname(process.argv[1] || __filename)
const mcpDir = path.dirname(scriptDir)
const docsRoot = path.join(mcpDir, '../llm-docs/tnui')
const outputFile = path.join(scriptDir, '../src/embedded-docs.ts')

// Interfaces
interface EmbeddedDoc {
  uri: string
  name: string
  description: string
  mimeType: string
  content: string
}

// Read directory recursively
function readDirRecursive(dir: string, baseUri: string = ''): EmbeddedDoc[] {
  const docs: EmbeddedDoc[] = []
  const items = fs.readdirSync(dir, { withFileTypes: true })

  for (const item of items) {
    const fullPath = path.join(dir, item.name)

    if (item.isDirectory()) {
      // Recursively read subdirectories
      const subDocs = readDirRecursive(fullPath, `${baseUri}/${item.name}`)
      docs.push(...subDocs)
    } else if (item.name.endsWith('.md')) {
      // Read markdown file
      const content = fs.readFileSync(fullPath, 'utf8')
      const relativePath = path.relative(docsRoot, fullPath)
      const name = relativePath.replace(/\\/g, '/').replace(/\.md$/, '')
      const uri = `tuniao://tnui/${name}`

      // Extract description from first line or use filename
      const firstLine = content.split('\n')[0].replace(/^#\s*/, '')
      const description = firstLine || name

      docs.push({
        uri,
        name: path.basename(name),
        description,
        mimeType: 'text/markdown',
        content,
      })
    }
  }

  return docs
}

// Parse component index to get structured component list
function parseComponentIndex(indexPath: string): any[] {
  if (!fs.existsSync(indexPath)) {
    return []
  }

  const content = fs.readFileSync(indexPath, 'utf8')
  const components: any[] = []

  // Parse categories and components
  const categoryRegex = /## (.+?) Components\n\n([\s\S]*?)(?=\n## |$)/g
  let match

  while ((match = categoryRegex.exec(content)) !== null) {
    const category = match[1].toLowerCase().replace(/\s+/g, '-')
    const sectionContent = match[2]

    // Parse component lines
    const componentRegex = /- \[([^\]]+)\]\(\.\/components\/([^)]+)\.md\):\s*(.+)/g
    let componentMatch

    while ((componentMatch = componentRegex.exec(sectionContent)) !== null) {
      components.push({
        name: componentMatch[1],
        category,
        description: componentMatch[3].trim(),
      })
    }
  }

  return components
}

// Main function
function embedDocs() {
  console.log('Embedding TNUI documentation...')

  // Check if docs directory exists
  if (!fs.existsSync(docsRoot)) {
    console.error(`Docs directory not found: ${docsRoot}`)
    process.exit(1)
  }

  // Read all documentation
  const allDocs = readDirRecursive(docsRoot)

  // Parse component index
  const indexPath = path.join(docsRoot, 'component-index.md')
  const components = parseComponentIndex(indexPath)

  // Create TypeScript content
  const output = `// This file is auto-generated by scripts/embed-docs.ts
// Do not edit manually

export interface EmbeddedDoc {
  uri: string
  name: string
  description: string
  mimeType: string
  content: string
}

export interface EmbeddedComponent {
  name: string
  category: string
  description: string
}

// All embedded documentation
export const embeddedDocs: EmbeddedDoc[] = ${JSON.stringify(allDocs, null, 2)}

// Component index
export const embeddedComponents: EmbeddedComponent[] = ${JSON.stringify(components, null, 2)}

// Component index content
export const componentIndexContent = \`${fs
    .readFileSync(indexPath, 'utf8')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$')}\`
`

  // Write output file
  fs.writeFileSync(outputFile, output, 'utf8')
  console.log(`Embedded ${allDocs.length} documents into ${outputFile}`)
}

// Run if called directly
if (process.argv[1]?.includes('embed-docs')) {
  embedDocs()
}
